// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RecruitX.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250522090725_client_loaction")]
    partial class client_loaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecruitX.Models.Clients", b =>
                {
                    b.Property<int>("Client_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Client_Id"));

                    b.Property<string>("Client_Country")
                        .HasColumnType("text")
                        .HasColumnName("client_country");

                    b.Property<string>("Client_Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.HasKey("Client_Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Locations", b =>
                {
                    b.Property<int>("Location_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Location_Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("client_country");

                    b.Property<string>("Location_Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.HasKey("Location_Id");

                    b.ToTable("locations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
