// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RecruitX.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523112620_correction2")]
    partial class correction2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.Property<int>("JobRequisition_Id")
                        .HasColumnType("integer");

                    b.Property<int>("JobSkill_Id")
                        .HasColumnType("integer");

                    b.Property<int>("JobRequisition_Id1")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("JobRequisition_Id", "JobSkill_Id");

                    b.HasIndex("JobRequisition_Id1");

                    b.HasIndex("SkillId");

                    b.ToTable("job_skill", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Client", b =>
                {
                    b.Property<int>("Client_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Client_Id"));

                    b.Property<string>("Client_Country")
                        .HasColumnType("text")
                        .HasColumnName("client_country");

                    b.Property<string>("Client_Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.HasKey("Client_Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeliveryUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("delivery_unit");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<long?>("Phone")
                        .HasColumnType("bigint")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("EmployeeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.JobDescription", b =>
                {
                    b.Property<int>("JdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JdId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int?>("CreatedByEmployeeEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("FillPositions")
                        .HasColumnType("integer")
                        .HasColumnName("fill_positions");

                    b.Property<string>("JobDesc")
                        .HasColumnType("text")
                        .HasColumnName("job_desc");

                    b.Property<int>("JobRequisition_Id")
                        .HasColumnType("integer")
                        .HasColumnName("jr_id");

                    b.Property<int?>("JobRequisition_Id1")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Updates")
                        .HasColumnType("text")
                        .HasColumnName("updates");

                    b.HasKey("JdId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByEmployeeEmployeeId");

                    b.HasIndex("JobRequisition_Id");

                    b.HasIndex("JobRequisition_Id1");

                    b.ToTable("job_descriptions", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.JobRequisition", b =>
                {
                    b.Property<int>("JobRequisition_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobRequisition_Id"));

                    b.Property<bool?>("Billable")
                        .HasColumnType("boolean");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<bool?>("ClientInterview")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpectedOnboardingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedSalaryRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("HiringManager")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IdealStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JdStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("JobPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobSpecification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("NumPositions")
                        .HasColumnType("integer");

                    b.Property<bool>("OnsiteOpportunity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProjectRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("RelevantExperienceRequired")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int?>("RequestedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("TotalExperienceRequired")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("WorkModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WorkShift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("JobRequisition_Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HiringManager");

                    b.HasIndex("LocationId");

                    b.HasIndex("RequestedBy");

                    b.ToTable("job_requisitions", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.JrAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("AssignedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by");

                    b.Property<long>("AssignedTo")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_to");

                    b.Property<int>("JobRequisition_Id")
                        .HasColumnType("integer")
                        .HasColumnName("jr_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("JobRequisition_Id");

                    b.ToTable("jr_assignments", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Location", b =>
                {
                    b.Property<int>("Location_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Location_Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Location_Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.HasKey("Location_Id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.OnSiteDetail", b =>
                {
                    b.Property<int>("OnsiteDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("onsite_detail_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OnsiteDetailId"));

                    b.Property<string>("ClientBackground")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_background");

                    b.Property<string>("ContractDuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contract_duration");

                    b.Property<string>("ContractType")
                        .HasColumnType("text")
                        .HasColumnName("contract_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("H1TransferAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("h1_transfer_accepted");

                    b.Property<DateTime>("IdealStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ideal_start_date");

                    b.Property<string>("InterviewProcess")
                        .HasColumnType("text")
                        .HasColumnName("interview_process");

                    b.Property<int>("JrId")
                        .HasColumnType("integer")
                        .HasColumnName("jr_id");

                    b.Property<string>("PreferredTimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_time_zone");

                    b.Property<string>("PreferredVisaStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_visa_status");

                    b.Property<string>("Rate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rate");

                    b.Property<string>("ReportingTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reporting_to");

                    b.Property<bool?>("TravelRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("travel_required");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OnsiteDetailId");

                    b.HasIndex("JrId")
                        .IsUnique();

                    b.ToTable("on_site_details", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_name");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("RecruitX.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.HasOne("RecruitX.Models.JobRequisition", "JobRequisition")
                        .WithMany()
                        .HasForeignKey("JobRequisition_Id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitX.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRequisition");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitX.Models.Employee", b =>
                {
                    b.HasOne("RecruitX.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitX.Models.JobDescription", b =>
                {
                    b.HasOne("RecruitX.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("RecruitX.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeEmployeeId");

                    b.HasOne("RecruitX.Models.JobRequisition", null)
                        .WithMany()
                        .HasForeignKey("JobRequisition_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitX.Models.JobRequisition", "JobRequisition")
                        .WithMany()
                        .HasForeignKey("JobRequisition_Id1");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("RecruitX.Models.JobRequisition", b =>
                {
                    b.HasOne("RecruitX.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.Employee", "HiringManagerEmployee")
                        .WithMany()
                        .HasForeignKey("HiringManager")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitX.Models.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("HiringManagerEmployee");

                    b.Navigation("Location");

                    b.Navigation("RequestedByEmployee");
                });

            modelBuilder.Entity("RecruitX.Models.JrAssignment", b =>
                {
                    b.HasOne("RecruitX.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecruitX.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecruitX.Models.JobRequisition", "JobRequisition")
                        .WithMany()
                        .HasForeignKey("JobRequisition_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("JobRequisition");
                });

            modelBuilder.Entity("RecruitX.Models.OnSiteDetail", b =>
                {
                    b.HasOne("RecruitX.Models.JobRequisition", "JobRequisition")
                        .WithOne()
                        .HasForeignKey("RecruitX.Models.OnSiteDetail", "JrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OnsiteJobDetail_JobRequisition");

                    b.Navigation("JobRequisition");
                });
#pragma warning restore 612, 618
        }
    }
}
